// Entity schemas — field names match the Supabase tables exactly (do not rename).
// Drives tables, drawers, forms, and the Excel importer.
import { LISTS } from './status'

export const SCHEMAS = {
  shipments: {
    key: 'shipments', table: 'shipments', title: 'משלוחים', icon: 'Ship',
    defaultSort: { column: 'eta', direction: 'ascending' },
    fields: [
      { k: 'order_status', l: 'סטטוס הזמנה', t: 'select', opts: LISTS.orderStatus, req: true, badge: true, group: 'הזמנה' },
      { k: 'supplier_no', l: 'מספר ספק', group: 'הזמנה' },
      { k: 'supplier_name', l: 'שם הספק', req: true, group: 'הזמנה' },
      { k: 'product', l: 'מוצר', req: true, wide: true, group: 'הזמנה' },
      { k: 'goods_cost', l: 'עלות סחורה ($)', t: 'number', group: 'עלויות' },
      { k: 'freight_cost', l: 'עלות משלוח ($)', t: 'number', group: 'עלויות' },
      { k: 'status', l: 'סטטוס משלוח', t: 'select', opts: LISTS.shipmentStatus, req: true, badge: true, group: 'משלוח' },
      { k: 'ship_type', l: 'סוג משלוח', t: 'select', opts: LISTS.shipType, badge: true, group: 'משלוח' },
      { k: 'prod_end', l: 'צפי סיום ייצור', t: 'date', group: 'משלוח' },
      { k: 'etd', l: 'ETD — יציאה', t: 'date', group: 'משלוח' },
      { k: 'eta', l: 'ETA — הגעה', t: 'date', group: 'משלוח' },
      { k: 'destination', l: 'יעד סחורה', group: 'משלוח' },
      { k: 'container_size', l: 'גודל מכולה', t: 'select', opts: LISTS.containerSize, group: 'משלוח' },
      { k: 'box_count', l: 'כמות ארגזים', t: 'number', group: 'משלוח' },
      { k: 'container_no', l: 'מספר מכולה', group: 'משלוח' },
      { k: 'tafnit_po', l: 'הזמנת רכש תפנית', group: 'תפנית ועמיל' },
      { k: 'tafnit_shipment_no', l: 'מספר משלוח תפנית', group: 'תפנית ועמיל' },
      { k: 'tafnit_last_status', l: 'סטטוס אחרון בתפנית', group: 'תפנית ועמיל' },
      { k: 'broker_file', l: 'מספר תיק עמיל', group: 'תפנית ועמיל' },
      { k: 'broker', l: 'עמיל', group: 'תפנית ועמיל' },
      { k: 'notes', l: 'הערות', t: 'textarea', wide: true, group: 'הערות' },
    ],
    cols: ['order_status', 'supplier_name', 'product', 'status', 'eta', 'goods_cost', 'destination', 'broker'],
    filters: [
      { k: 'order_status', l: 'סטטוס הזמנה', opts: LISTS.orderStatus },
      { k: 'status', l: 'סטטוס משלוח', opts: LISTS.shipmentStatus },
      { k: 'ship_type', l: 'סוג משלוח', opts: LISTS.shipType },
    ],
    titleField: 'product', subtitleField: 'supplier_name',
    cardCols: ['supplier_name', 'status', 'eta', 'goods_cost'],
  },
  payments: {
    key: 'payments', table: 'payments', title: 'תשלומים', icon: 'CreditCard',
    defaultSort: { column: 'advance_date', direction: 'descending' },
    fields: [
      { k: 'status', l: 'סטטוס תשלום', t: 'select', opts: LISTS.payStatus, req: true, badge: true, group: 'תשלום' },
      { k: 'manufacturer', l: 'יצרן', group: 'תשלום' },
      { k: 'supplier_no', l: 'מספר ספק', group: 'תשלום' },
      { k: 'details', l: 'פירוט', req: true, wide: true, group: 'תשלום' },
      { k: 'order_no', l: 'מספר הזמנה', group: 'תשלום' },
      { k: 'category', l: 'קטגוריית מוצרים', group: 'תשלום' },
      { k: 'pay_type', l: 'סוג תשלום', t: 'select', opts: LISTS.payType, group: 'תשלום' },
      { k: 'invoice_total', l: 'מחיר חשבונית מלא ($)', t: 'number', group: 'סכומים' },
      { k: 'advance_date', l: 'תאריך שליחת מקדמה', t: 'date', group: 'סכומים' },
      { k: 'advance_amount', l: 'סכום לתשלום מיידי ($)', t: 'number', group: 'סכומים' },
      { k: 'balance_date', l: 'תאריך שליחת יתרה', t: 'date', group: 'סכומים' },
      { k: 'balance_amount', l: 'יתרה לאחר ייצור ($)', t: 'number', group: 'סכומים' },
    ],
    cols: ['status', 'manufacturer', 'details', 'order_no', 'invoice_total', 'advance_date', 'advance_amount'],
    filters: [
      { k: 'status', l: 'סטטוס תשלום', opts: LISTS.payStatus },
      { k: 'pay_type', l: 'סוג תשלום', opts: LISTS.payType },
    ],
    titleField: 'details', subtitleField: 'manufacturer',
    cardCols: ['manufacturer', 'status', 'invoice_total', 'advance_date'],
  },
  suppliers: {
    key: 'suppliers', table: 'suppliers', title: 'ספקים', icon: 'Factory',
    defaultSort: { column: 'tafnit_no', direction: 'ascending' },
    fields: [
      { k: 'name', l: 'שם ספק', req: true, group: 'ספק' },
      { k: 'description', l: 'תיאור', group: 'ספק' },
      { k: 'supplier_type', l: 'סוג ספק', t: 'select', opts: LISTS.supplierType, badge: true, group: 'ספק' },
      { k: 'tafnit_no', l: 'מס ספק תפנית', group: 'מספרי תפנית' },
      { k: 'account_no', l: 'מס ספק חשבונות', group: 'מספרי תפנית' },
      { k: 'transit_no', l: 'מספר סחורה בדרך', group: 'מספרי תפנית' },
    ],
    cols: ['tafnit_no', 'name', 'description', 'supplier_type', 'account_no'],
    filters: [{ k: 'supplier_type', l: 'סוג ספק', opts: LISTS.supplierType }],
    titleField: 'name', subtitleField: 'description',
    cardCols: ['supplier_type', 'tafnit_no', 'description'],
  },
  products: {
    key: 'products', table: 'products', title: 'מקטים', icon: 'Package',
    defaultSort: { column: 'inner_sku', direction: 'ascending' },
    fields: [
      { k: 'inner_sku', l: 'מקט פנימי (INNER SKU)', req: true, group: 'מקט' },
      { k: 'product_name', l: 'שם מוצר / מקט יצרן', group: 'מקט' },
      { k: 'desc_he', l: 'תיאור בעברית', req: true, wide: true, group: 'תיאור' },
      { k: 'desc_en', l: 'תיאור באנגלית', wide: true, group: 'תיאור' },
      { k: 'manufacturer', l: 'יצרן', group: 'ספק' },
      { k: 'supplier_tafnit_no', l: 'מס ספק תפנית', group: 'ספק' },
    ],
    cols: ['inner_sku', 'desc_he', 'desc_en', 'manufacturer', 'supplier_tafnit_no'],
    filters: [],
    titleField: 'desc_he', subtitleField: 'inner_sku',
    cardCols: ['inner_sku', 'manufacturer', 'supplier_tafnit_no'],
  },
}
